# Generated by Django 4.1.7 on 2023-02-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coupon_Rate', models.FloatField()),
                ('ISIN', models.FloatField()),
                ('Name_of_the_Security', models.CharField(max_length=225)),
                ('CATEGORY', models.CharField(max_length=225)),
                ('Rating_Agency', models.CharField(max_length=225)),
                ('Maturity_Date', models.CharField(max_length=225)),
                ('IP_Dates', models.CharField(max_length=225)),
                ('Put_Call_Option', models.CharField(max_length=225)),
                ('Price_Per_100', models.FloatField()),
                ('YTM', models.FloatField()),
                ('YTC_YTP', models.FloatField()),
                ('Face_Value', models.IntegerField()),
                ('Quantum', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='upload',
        ),
    ]
