# Generated by Django 4.1.7 on 2023-03-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_productbrand_delete_document_delete_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productfield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coupon_Rate', models.FloatField()),
                ('ISIN', models.TextField()),
                ('Name_of_the_security', models.CharField(max_length=225)),
                ('CATEGORY', models.CharField(max_length=225)),
                ('Rating_Agency', models.CharField(max_length=225)),
                ('Maturity_Date', models.CharField(max_length=225)),
                ('IP_Dates', models.CharField(max_length=225)),
                ('Put_Call_Option', models.TextField()),
                ('Price_Per_100', models.FloatField()),
                ('YTM', models.FloatField()),
                ('YTC_YTP', models.TextField()),
                ('Face_Value', models.CharField(max_length=225)),
                ('Quantum', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductBrand',
        ),
    ]
